Fixed exit conditions

diff --git a/templates/jobs/delete-all.sh.erb b/templates/jobs/delete-all.sh.erb
--- a/templates/jobs/delete-all.sh.erb
+++ b/templates/jobs/delete-all.sh.erb
@@ -1,23 +1,23 @@
 #!/bin/bash
 
-set -e
+export CF=`which cf`
 
 function cf() {
-	CF=`which cf`
-	if [ "$1" == "--output" ]; then
-		shift
-		echo cf "$@"
-		$CF "$@"
-		result=$?
-	else
-		echo cf "$@"
-		output=`$CF "$@" 2>&1`
-		result=$?
-		if [ "$result" -ne "0" ]; then
-			echo "$output"
-		fi
+	echo cf "$@"
+	output=$($CF "$@" 2>&1)
+	result="$?"
+	if [ "$result" -ne "0" ]; then
+		echo "$output"
+		# No exit here - best effort continuation on failure for the delete script
 	fi
-	return $result
+}
+
+function is_true() {
+	equals_ignore_case "$1" "true"
+}
+
+function equals_ignore_case() {
+	echo "$1" | grep -i "^$2\$" >/dev/null
 }
 
 function import_opsmgr_variables() {
@@ -39,8 +39,8 @@ function prepare_cf_cli {
 }
 
 function authenticate() {
-	cf --output --version
-	if [ "$CF_SKIP_SSL" == "true" -o "$CF_SKIP_SSL" == "True" ]; then
+	$CF --version
+	if is_true "$CF_SKIP_SSL"; then
 		cf api $CF_TARGET --skip-ssl-validation
 	else
 		cf api $CF_TARGET
@@ -52,42 +52,40 @@ function target_org() {
 	if [ -z "$CF_ORG" ]; then
 		CF_ORG={{ context.name }}-org
 	fi
-	ignore=`cf target -o $CF_ORG`
-	return $?
+	cf target -o $CF_ORG >/dev/null
 }
 
 function target_space() {
 	if [ -z "$CF_SPACE" ]; then
 		CF_SPACE={{ context.name }}-space
 	fi
-	ignore=`cf target -s $CF_SPACE`
-	return $?
+	cf target -s $CF_SPACE >/dev/null
 }
 
 function delete_empty_space() {
-	output=`cf --output apps | tail -1`
+	output=`$CF apps | tail -1`
 	if [ "$output" == "No apps found" ]; then
 		cf delete-space -f $CF_SPACE
 	fi
 }
 
 function delete_empty_org() {
-	output=`cf --output spaces | tail -1`
+	output=`$CF spaces | tail -1`
 	if [ "$output" == "No spaces found" ]; then
 		cf delete-org -f $CF_ORG
 	fi
 }
 
 function delete_all_versions() {
-	cf --output apps | grep "$1-" | while read app rest; do
+	$CF apps | grep "$1-" | while read app rest; do
 		cf delete -f $app
 	done
 }
 
 function delete_service_broker() {
-    services=`cf service-access | awk "/broker: $1/{flag=1;next}/broker: /{flag=0}flag" | egrep -v "access *orgs" | grep "."  | awk '{print $1}' | uniq `
-    for service_name in "$services"; do
-      cf purge-service-offering -f $service_name
+    services=`$CF service-access | awk "/broker: $1/{flag=1;next}/broker: /{flag=0}flag" | egrep -v "access *orgs" | grep "."  | awk '{print $1}' | uniq`
+    for service in $services; do
+      cf purge-service-offering -f "$service"
     done
     cf delete-service-broker -f $1
 }
